# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '导出所有用户数据',
                'verbose_name_plural': '导出所有用户数据',
            },
        ),
        migrations.CreateModel(
            name='ZAutoReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField(verbose_name='文本消息内容')),
                ('msg_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片消息内容')),
                ('msg_image_for_huanxin', models.ImageField(blank=True, null=True, upload_to='', verbose_name='环信平台的图片消息内容')),
                ('image_uuid', models.TextField(blank=True, null=True, verbose_name='图片上传环信后的uuid')),
                ('image_type', models.TextField(blank=True, null=True, verbose_name='图片上传环信后的type')),
                ('image_share_secret', models.TextField(blank=True, null=True, verbose_name='图片上传环信后的share_secret')),
            ],
            options={
                'verbose_name': '自动回复内容',
                'verbose_name_plural': '自动回复内容',
            },
        ),
        migrations.CreateModel(
            name='ZBeiZhuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, verbose_name='使用备注者')),
                ('friend_name', models.CharField(blank=True, max_length=50, verbose_name='被备注者')),
                ('beizhu_name', models.CharField(blank=True, max_length=50, verbose_name='备注名')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '备注',
                'verbose_name_plural': '备注',
            },
        ),
        migrations.CreateModel(
            name='ZUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别(1男2女)')),
                ('signature', models.CharField(blank=True, max_length=50, null=True, verbose_name='签名')),
                ('head', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='1普通用户,2会员')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='1正常,2禁用,3删除')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('atime', models.DateField(blank=True, null=True, verbose_name='有效时间')),
                ('stature', models.CharField(blank=True, max_length=50, null=True, verbose_name='身高')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='行业')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历')),
                ('is_service', models.BooleanField(default=False, verbose_name='是否客服')),
                ('mtime', models.DateField(blank=True, null=True, verbose_name='最后一次登录/修改时间')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注(取好友信息时计算,对好友的备注)')),
            ],
            options={
                'verbose_name': '聊天App用户',
                'verbose_name_plural': '聊天App用户',
            },
        ),
    ]
