# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZXChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZXUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('sex', models.IntegerField(null=True)),
                ('signature', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
                ('head', models.CharField(max_length=50, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('type', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('ctime', models.CharField(max_length=50, null=True)),
                ('mtime', models.CharField(max_length=50, null=True)),
                ('stature', models.CharField(max_length=50, null=True)),
                ('birthday', models.CharField(max_length=50, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('is_service', models.IntegerField(null=True)),
            ],
        ),
    ]
