# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': 'admin中跳转自定义的xx',
                'verbose_name_plural': 'admin中跳转自定义的xx',
            },
        ),
        migrations.CreateModel(
            name='MyChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别(1男2女)')),
                ('signature', models.CharField(blank=True, max_length=50, null=True, verbose_name='个性签名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('headimage', models.CharField(blank=True, max_length=50, null=True, verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '聊天App用户',
                'verbose_name_plural': '聊天App用户',
            },
        ),
    ]
